// AUTO-GENERATED by scripts/gen-thumbnails.js — do not edit by hand.
// Add images to assets/thumbnails/ named <prompt-id>.<ext>, then re-run the script.
import type { ImageSourcePropType } from 'react-native';

export const THUMBNAILS: Record<string, ImageSourcePropType> = {
  'portrait-studio-glow': require('../assets/thumbnails/portrait-studio-glow.webp'),
};

export function getThumbnail(promptId: string): ImageSourcePropType | undefined {
  return THUMBNAILS[promptId];
}
