// AUTO-GENERATED by scripts/gen-thumbnails.js — do not edit by hand.
// Add images to assets/thumbnails/ then re-run: node scripts/gen-thumbnails.js
//   <id>.<ext>          single thumbnail
//   <id>-before.<ext>   + <id>-after.<ext>  interactive before/after slider
import type { ImageSourcePropType } from 'react-native';

export const THUMBNAILS: Record<string, ImageSourcePropType> = {
  'portrait-studio-glow': require('../assets/thumbnails/portrait-studio-glow-after.webp'),
};

export interface BeforeAfterPair {
  before: ImageSourcePropType;
  after: ImageSourcePropType;
}

export const BEFORE_AFTER: Record<string, BeforeAfterPair> = {
  'portrait-studio-glow': { before: require('../assets/thumbnails/portrait-studio-glow-before.webp'), after: require('../assets/thumbnails/portrait-studio-glow-after.webp') },
};

export function getThumbnail(promptId: string): ImageSourcePropType | undefined {
  return THUMBNAILS[promptId];
}

export function getBeforeAfter(promptId: string): BeforeAfterPair | undefined {
  return BEFORE_AFTER[promptId];
}
